# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

env:
  global:
    - MODULE_NAME=EthereumTypes

# Run tests on Ubuntu and macOS
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: objective-c
      sudo: required
      before_install:
        - instruments -s devices
        - gem install cocoapods
        - pod repo update
      script:
        - set -o pipefail && xcodebuild test -project $MODULE_NAME.xcodeproj -scheme $MODULE_NAME-macOS ONLY_ACTIVE_ARCH=YES | xcpretty
        - set -o pipefail && xcodebuild test -project $MODULE_NAME.xcodeproj -scheme $MODULE_NAME-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' ONLY_ACTIVE_ARCH=YES | xcpretty
        - set -o pipefail && xcodebuild test -project $MODULE_NAME.xcodeproj -scheme $MODULE_NAME-tvOS -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV' ONLY_ACTIVE_ARCH=YES | xcpretty
        - set -o pipefail && xcodebuild build -project $MODULE_NAME.xcodeproj -scheme $MODULE_NAME-watchOS -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm' ONLY_ACTIVE_ARCH=YES | xcpretty
        - swift build
        - swift build -c release
        - swift test
        # Output something every 10 minutes or Travis kills the job
        - while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - pod lib lint --allow-warnings --fail-fast
        # Kill background echo job
        - kill %1
    - os: linux
      # Ubuntu 14.04
      dist: trusty
      # Generic language as travis doesn't know anything about SPM and Linux
      language: generic
      before_install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift build
        - swift build -c release
        - swift test
