#if !canImport(ObjectiveC)
import XCTest

extension EthereumTypesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EthereumTypesTests = [
        ("testExample", testExample),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EthereumTypesTests.__allTests__EthereumTypesTests),
    ]
}
#endif
