#if !canImport(ObjectiveC)
import XCTest

extension ABIConvertibleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ABIConvertibleTests = [
        ("testAddress", testAddress),
        ("testArray", testArray),
        ("testBool", testBool),
        ("testData", testData),
        ("testSignedIntegers", testSignedIntegers),
        ("testSignedIntegersDecodeHex", testSignedIntegersDecodeHex),
        ("testSignedIntegersEncodeHex", testSignedIntegersEncodeHex),
        ("testSolidityRepresentable", testSolidityRepresentable),
        ("testString", testString),
        ("testUnsignedIntegers", testUnsignedIntegers),
    ]
}

extension SolidityTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SolidityTypeTests = [
        ("testDecodingAddressType", testDecodingAddressType),
        ("testDecodingArrayType", testDecodingArrayType),
        ("testDecodingBoolType", testDecodingBoolType),
        ("testDecodingBytesType", testDecodingBytesType),
        ("testDecodingNumberTypes", testDecodingNumberTypes),
        ("testDecodingStringType", testDecodingStringType),
    ]
}

extension SolidityWrappedValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SolidityWrappedValueTests = [
        ("testAddress", testAddress),
        ("testArray", testArray),
        ("testBool", testBool),
        ("testBytes", testBytes),
        ("testInt", testInt),
        ("testNestedArray", testNestedArray),
        ("testString", testString),
        ("testUInt", testUInt),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ABIConvertibleTests.__allTests__ABIConvertibleTests),
        testCase(SolidityTypeTests.__allTests__SolidityTypeTests),
        testCase(SolidityWrappedValueTests.__allTests__SolidityWrappedValueTests),
    ]
}
#endif
